sudo: required

services:
  - docker

install: true

addons:
  ssh_known_hosts: 82.202.221.10

before_install:
- openssl aes-256-cbc -K $encrypted_87a0b5313f5d_key -iv $encrypted_87a0b5313f5d_iv
   -in deploy_rsa.enc -out /tmp/deploy_rsa -d

before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ root@82.202.221.10:root/wb
  on:
    branch: master
