sudo: required
services:
- docker
install: true
addons:
  ssh_known_hosts: 82.202.204.246
before_install:
- openssl aes-256-cbc -K $encrypted_87a0b5313f5d_key -iv $encrypted_87a0b5313f5d_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
script:
- echo "Script"
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --exclude 'data' --exclude 'static' --exclude 'media' --delete-after
    --quiet $TRAVIS_BUILD_DIR/ root@82.202.204.246:wb && ssh root@82.202.204.246 -C
    "cd wb && PYTHONPATH=src/ python3 src/database/init_db.py && docker-compose up"
  on:
    branch: master
