sudo: required
services:
- docker
install: true
addons:
  ssh_known_hosts: 84.201.155.216
before_install:
- openssl aes-256-cbc -K $encrypted_ed05735a344a_key -iv $encrypted_ed05735a344a_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
script:
- echo "Script"
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --exclude 'data' --exclude 'static' --exclude 'media' --delete-after
    --quiet $TRAVIS_BUILD_DIR/ root@84.201.155.216:wb && ssh root@84.201.155.216 -C
    "docker-compose up --build -d"
  on:
    branch: master
