version: '3'
services:

  postgres:
    restart: always
    image: postgres:latest
    networks:
      - backend
    ports:
      - 5454:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./dumps:/dumps
    environment:
      - POSTGRES_DB=wb
      - POSTGRES_USER=wb
      - POSTGRES_PASSWORD=wb

#psql postgresql://wb:wb@localhost:5454/wb

  backend:
    build: .
    networks:
      - backend
    ports:
      - 8080:8080

    stdin_open: true
    tty: true

    volumes:
      - ./:/app/
      - ./etc:/app/etc
      - ./tests:/app/tests
      - ./setup.cfg:/app/setup.cfg
      - ./setup.py:/app/setup.py

    environment:
      - PYTHONPATH=/src

    links:
      - postgres

  frontend-builder:
    build:
      context: ./weird_brains_frontend/
    volumes:
      - ./static:/static

  nginx:
    restart: always
    build:
      context: nginx/
    volumes:
      - ./static:/static
      - ./admin:/admin
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    links:
      - backend


networks:
  frontend:
  backend:
